package com.example.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.dynamo.model.Address;
import lombok.Builder;
import lombok.Data;

import java.io.Serializable;

@Data
@Builder
@DynamoDBTable(tableName = "student")
public class Student implements Serializable {

	@DynamoDBHashKey(attributeName = "studentId")
	@DynamoDBAutoGeneratedKey
	private String studentId;

	@DynamoDBAttribute
	private String firstName;

	@DynamoDBRangeKey
	private String lastName;

	@DynamoDBAttribute
	private int age;

	@DynamoDBAttribute
	private Address address;
}
